language: bash
sudo: required
dist: xenial
env:
- OS=debian ARCH=amd64 DIST=buster
- OS=debian ARCH=i386 DIST=buster
- OS=debian ARCH=armhf DIST=buster
- OS=raspbian ARCH=armhf DIST=buster
- OS=debian ARCH=armel DIST=buster
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository -y ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes pbuilder-ev3dev gobject-introspection
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-buster
script:
- pbuilder-ev3dev build
